/***************************************************************************
 *            pcSyncProcessDataSingle.cc
 *
 *  Sun Jul 22 23:14:14 2007
 *  Copyright  2007  Ni@m
 *  niam.niam@gmail.com
 ****************************************************************************/

/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License version 2.1 as published by
 *  the Free Software Foundation;
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/**
 * vim indentation settings
 * set tabstop=4
 * set shiftwidth=4
 */


#include <libdodo/pcSyncProcessDataSingle.h>

using namespace dodo::pc::sync::process::data;

single::single(single &sts)
{
}

//-------------------------------------------------------------------

single::single(int a_key) : data(NULL),
										 autogenerated(false),
										 acquired(false),
#ifdef XSI_SEMAPHORES

										 keeper(-1)

#else

										 keeper(NULL)

#endif
{
#ifdef XSI_SEMAPHORES

	if (a_key == 0)
	{
		key = tools::misc::iRandom();

		autogenerated = true;
	}
	else
		key = a_key;

	operations[0].sem_num = 0;
	operations[0].sem_flg = 0;

#else

	key = '/';

	if (a_key == 0)
	{
		char _key[SH_KEY_SIZE / 2 - 1];
		tools::misc::random(_key, SH_KEY_SIZE / 2 - 1);

		key.append(tools::code::binToHex(dodoString(_key, SH_KEY_SIZE / 2 - 1)));

		autogenerated = true;
	}
	else
	{
		char _key[4];
		memcpy(_key, &a_key, 4);

		key.append(tools::code::binToHex(dodoString(_key, 4)));
	}

#endif
}

//-------------------------------------------------------------------

single::~single()
{
#ifdef XSI_SEMAPHORES

	if (keeper != -1)
	{
		if (autogenerated)
			semctl(keeper, 0, IPC_RMID, control);
		else
		{
			if (acquired)
			{
				operations[0].sem_op = -1;

				semop(keeper, operations, 1);
			}
		}
	}

#else

	if (keeper != NULL)
	{
		if (autogenerated)
		{
			sem_close(keeper);

			sem_unlink(key.c_str());
		}
		else
		{
			if (acquired)
				sem_post(keeper);

			sem_close(keeper);
		}
	}

#endif
}

//-------------------------------------------------------------------

void
single::remove(int a_key)
{
#ifdef XSI_SEMAPHORES

	int keeper = semget(a_key, 1, 0600);
	if (keeper == -1)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_REMOVE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

	if (semctl(keeper, 0, IPC_RMID, control) == -1)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_REMOVE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#else

	dodoString key = "/";

	char _key[4];
	memcpy(_key, &a_key, 4);

	key.append(tools::code::binToHex(dodoString(_key, 4)));

	if (keeper != NULL)
		if (sem_close(keeper) == -1)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_REMOVE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

	if (sem_unlink(key.c_str()) == -1)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_REMOVE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#endif
}

//-------------------------------------------------------------------

void
single::set(void *a_data)
{
#ifdef XSI_SEMAPHORES

	if (keeper == -1)
	{
		keeper = semget(key, 1, 0600 | IPC_CREAT);
		if (keeper == -1)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

		control.val = 0;

		if (semctl(keeper, 0, SETVAL, control) == -1)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}

	operations[0].sem_op = 0;

	if(semop(keeper, operations, 1) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

	operations[0].sem_op = 1;

	if(semop(keeper, operations, 1) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

	data = a_data;

	operations[0].sem_op = -1;

	if(semop(keeper, operations, 1) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#else

	if (keeper == NULL)
	{
		keeper = sem_open(key.c_str(), O_CREAT, 0600, 1);
		if (keeper == NULL)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}

	if (sem_wait(keeper) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

	data = a_data;

	if (sem_post(keeper) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_SET, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#endif
}

//-------------------------------------------------------------------

void
single::del()
{
	set(NULL);
}

//-------------------------------------------------------------------

void *
single::acquire(unsigned long microseconds)
{
#ifdef XSI_SEMAPHORES

	if (keeper == -1)
	{
		keeper = semget(key, 1, 0600 | IPC_CREAT);
		if (keeper == -1)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

		control.val = 0;

		if (semctl(keeper, 0, SETVAL, control) == -1)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}

	if (microseconds == 0)
	{
		operations[0].sem_op = 0;

		if(semop(keeper, operations, 1) != 0)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

		operations[0].sem_op = 1;

		if(semop(keeper, operations, 1) != 0)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}
	else
	{
		bool locked = true;
		unsigned long slept = 0;

		operations[0].sem_op = 0;
		operations[0].sem_flg = IPC_NOWAIT;

		while (locked)
		{
			if (semop(keeper, operations, 1) != 0)
			{
				if (errno != EAGAIN)
				{
					operations[0].sem_flg = 0;

					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
				}

				if (nanosleep(&timeout, NULL) == -1)
				{
					operations[0].sem_flg = 0;

					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
				}

				slept += 1;

				if (slept > microseconds)
				{
					operations[0].sem_flg = 0;

					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_LIBDODO, SINGLEEX_CANNOTLOCK, PCSYNCPROCESSDATASINGLEEX_CANNOTLOCK_STR, __LINE__, __FILE__);
				}
			}
			else
				locked = false;
		}

		operations[0].sem_op = 1;
		operations[0].sem_flg = 0;

		if(semop(keeper, operations, 1) != 0)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}

#else

	if (keeper == NULL)
	{
		keeper = sem_open(key.c_str(), O_CREAT, 0600, 1);
		if (keeper == NULL)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}

	if (microseconds == 0)
	{
		if (sem_wait(keeper) != 0)
			throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);
	}
	else
	{
		bool locked = true;
		unsigned long slept = 0;

		while (locked)
		{
			if (sem_trywait(keeper) != 0)
			{
				if (errno != EAGAIN)
					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

				if (nanosleep(&timeout, NULL) == -1)
					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

				slept += 1;

				if (slept > microseconds)
					throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_ACQUIRE, exception::ERRNO_LIBDODO, SINGLEEX_CANNOTLOCK, PCSYNCPROCESSDATASINGLEEX_CANNOTLOCK_STR, __LINE__, __FILE__);
			}
			else
				locked = false;
		}
	}


#endif

	acquired = true;

	return data;
}

//-------------------------------------------------------------------

void
single::release()
{
#ifdef XSI_SEMAPHORES

	if (keeper == -1)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_RELEASE, exception::ERRNO_LIBDODO, SINGLEEX_SEMAPHOREWASNOTOPENED, PCSYNCPROCESSDATASINGLEEX_SEMAPHOREWASNOTOPENED_STR, __LINE__, __FILE__);

	operations[0].sem_op = -1;

	if(semop(keeper, operations, 1) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_RELEASE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#else

	if (keeper == NULL)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_RELEASE, exception::ERRNO_LIBDODO, SINGLEEX_SEMAPHOREWASNOTOPENED, PCSYNCPROCESSDATASINGLEEX_SEMAPHOREWASNOTOPENED_STR, __LINE__, __FILE__);

	if (sem_post(keeper) != 0)
		throw exception::basic(exception::ERRMODULE_PCSYNCPROCESSDATASINGLE, SINGLEEX_RELEASE, exception::ERRNO_ERRNO, errno, strerror(errno), __LINE__, __FILE__);

#endif

	acquired = false;
}

//-------------------------------------------------------------------

